// Generates the dotted land map used by the hero and journey.
// Output is committed (lib/map-dots.ts), so these packages are dev-only.
import { readFileSync, writeFileSync } from "node:fs";
import { feature } from "topojson-client";
import { geoContains } from "d3-geo";

const topo = JSON.parse(readFileSync("node_modules/world-atlas/land-50m.json", "utf8"));
const land = feature(topo, topo.objects.land);

// Keep in sync with lib/geo.ts
const LON0 = 34, LON1 = 124, LAT0 = -4, LAT1 = 44;
const W = 1000;
const KX = W / (LON1 - LON0);
const KY = KX / Math.cos((22 * Math.PI) / 180);
const H = (LAT1 - LAT0) * KY;
const STEP = 8; // px between dots

// Encode dots compactly: absolute move at the first dot of each row, relative after that.
function encodeRows(rows) {
  let d = "";
  for (const r of rows) {
    if (!r.length) continue;
    d += `M${+r[0][0].toFixed(1)} ${+r[0][1].toFixed(1)}h0`;
    for (let i = 1; i < r.length; i++) d += `m${+(r[i][0] - r[i - 1][0]).toFixed(1)} 0h0`;
  }
  return d;
}
const rowsCoarse = [];
let n = 0;
for (let y = STEP / 2; y < H; y += STEP) {
  const row = Math.round(y / STEP);
  const offset = row % 2 ? STEP / 2 : 0; // staggered grid reads less mechanical
  const r = [];
  rowsCoarse.push(r);
  for (let x = STEP / 2 + offset; x < W; x += STEP) {
    const lon = LON0 + x / KX;
    const lat = LAT1 - y / KY;
    if (geoContains(land, [lon, lat])) {
      r.push([x, y]);
      n++;
    }
  }
}
const out = `// Generated by scripts/generate-map.mjs — do not edit by hand.
export const MAP_W = ${W};
export const MAP_H = ${H.toFixed(1)};
export const DOT_STEP = ${STEP};
export const LAND_DOTS = "${encodeRows(rowsCoarse)}";
`;
writeFileSync("lib/map-dots.ts", out);
console.log(`dots: ${n}, H=${H.toFixed(1)}, bytes=${out.length}`);

// Finer dots for the zoomed-in views (China and the Gulf). Loaded lazily.
function region([x0, y0, w, h], step) {
  const rows = [];
  let count = 0;
  for (let y = y0; y < y0 + h; y += step) {
    const row = Math.round((y - y0) / step);
    const off = row % 2 ? step / 2 : 0;
    const r = [];
    rows.push(r);
    for (let x = x0 + off; x < x0 + w; x += step) {
      const lon = LON0 + x / KX, lat = LAT1 - y / KY;
      if (geoContains(land, [lon, lat])) { r.push([x, y]); count++; }
    }
  }
  return { d: encodeRows(rows), count };
}
const china = region([660, 20, 340, 380], 3.4);
const gcc = region([40, 120, 300, 220], 2.8);
writeFileSync(
  "lib/map-fine.ts",
  `// Generated by scripts/generate-map.mjs — do not edit by hand.\nexport const FINE_STEP = { china: 3.4, gcc: 2.8 };\nexport const FINE_CHINA = "${china.d}";\nexport const FINE_GCC = "${gcc.d}";\n`
);
console.log(`fine dots: china ${china.count}, gcc ${gcc.count}`);
